# Generated by Django 5.0.6 on 2024-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Leisure', 'Leisure'), ('Other', 'Other')], max_length=40),
        ),
    ]
