# Generated by Django 5.0.6 on 2024-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expenses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
